name: Build Multi-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            output_name: inventory_system
          - os: windows-latest
            output_name: inventory_system.exe
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip --no-cache-dir
        pip install --no-cache-dir -r requirements.txt
        
    - name: Create icon
      shell: bash
      run: |
        cd src
        python create_icon.py
        
    - name: Build executable
      shell: bash
      run: |
        cd src
        python -m PyInstaller --noconfirm --onefile --windowed \
        --icon=inventory.ico \
        --name="inventory_system" \
        --add-data "inventory.ico:." \
        inventory_system.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: inventory-system-${{ runner.os }}
        path: src/dist/${{ matrix.output_name }}